<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <?php echo $this->headTitle(); ?>
        <script src="/js/jquery-1.8.3.min.js" type="text/javascript"></script>
        <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
        <link rel="stylesheet" href="/css/show-loading/showLoading.css" />
        <script src="/js/jquery.showLoading.min.js" type="text/javascript"></script>
        <!-- 引入bootstrap -->
        <link rel="stylesheet" href="/etp_style_v1.0/js/bootstrap/css/bootstrap.css" />
        <script type="text/javascript" src="/etp_style_v1.0/js/bootstrap/js/bootstrap.js"></script>
        <?php
            //引入bootstrap 分页
            if( isset( $this->layout()->includeBsPage ) && $this->layout()->includeBsPage ) {
                echo '<script type="text/javascript" src="/etp_style_v1.0/js/bootstrap/js/bootstrap-paginator.min.js"></script>';
            }
        ?>
        <?php
            //引入bootstrap 时间控件
            if( isset( $this->layout()->includeBsDate ) && $this->layout()->includeBsDate ) {
                echo '<link href="/etp_style_v1.0/js/bootstrap/plugins/datetimepicker/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">'; 
                echo '<script src="/etp_style_v1.0/js/bootstrap/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>';
                echo '<script src="/etp_style_v1.0/js/bootstrap/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>';
                echo '<script src="/etp_style_v1.0/js/bootstrap/plugins/datetimepicker/bootstrap-datetimepicker.js" type="text/javascript"></script>';
                echo '<script src="/etp_style_v1.0/js/bootstrap/plugins/datetimepicker/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8" type="text/javascript"></script>';
            }
        ?>
        <!--
        <link rel="stylesheet" href="/etp_style_v1.0/css/base.css" />
        -->
        <link rel="stylesheet" href="/etp_style_v1.0/css/style.css" />
        <link rel="stylesheet" href="/etp_style_v1.0/css/sample.css" />
        <link rel="stylesheet" href="/etp_style_v1.0/css/member.css" />
    </head>
    <body>

        <div class="m_topContainer">
            <?php echo $this->layout()->top;?>
        </div>
        <div class="m_headerContainer">
            <?php echo $this->layout()->innerHeader;?>
        </div>
        <div class="m_mainContainer">
            <?php echo $this->layout()->content;?>
        </div>
        <div class="m_footerContainer">
            <?php echo $this->layout()->footer;?>
        </div>
    </body>
</html>