<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
        <?php echo $this->headTitle(); ?>

        <script src="/js/jquery-1.8.3.min.js" type="text/javascript"></script>
        <script src="http://cdn.bootcss.com/jquery/1.11.1/jquery.min.js" type="text/javascript"></script>
        <link rel="stylesheet" href="/css/show-loading/showLoading.css" />
        <script src="/js/jquery.showLoading.min.js" type="text/javascript"></script>
        <!-- 引入bootstrap -->
        <link rel="stylesheet" href="/etp_style_v1.0/js/bootstrap/css/bootstrap.css" />
        <script type="text/javascript" src="/etp_style_v1.0/js/bootstrap/js/bootstrap.js"></script>
        <?php
            //引入bootstrap 分页
            if( isset( $this->layout()->includeBsPage ) && $this->layout()->includeBsPage ) {
                echo '<script type="text/javascript" src="/etp_style_v1.0/js/bootstrap/js/bootstrap-paginator.min.js"></script>'."\n";
                echo '<script type="text/javascript" src="/etp_style_v1.0/js/common-page.js"></script>'."\n";
            }
        ?>
        <?php
            //引入bootstrap 时间控件
            if( isset( $this->layout()->includeBsDate ) && $this->layout()->includeBsDate ) {
                echo '<link href="/etp_style_v1.0/js/bootstrap/plugins/datetimepicker/bootstrap-datetimepicker.min.css" rel="stylesheet" media="screen">'."\n"; 
                echo '<script src="/etp_style_v1.0/js/bootstrap/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>'."\n";
                echo '<script src="/etp_style_v1.0/js/bootstrap/plugins/datepicker/bootstrap-datepicker.js" type="text/javascript"></script>'."\n";
                echo '<script src="/etp_style_v1.0/js/bootstrap/plugins/datetimepicker/bootstrap-datetimepicker.js" type="text/javascript"></script>'."\n";
                echo '<script src="/etp_style_v1.0/js/bootstrap/plugins/datetimepicker/locales/bootstrap-datetimepicker.zh-CN.js" charset="UTF-8" type="text/javascript"></script>'."\n";
            }
        ?>
        <!--
        <link rel="stylesheet" href="/etp_style_v1.0/css/base.css" />
        -->
        <link rel="stylesheet" href="/etp_style_v1.0/css/style.css" />
        <link rel="stylesheet" href="/etp_style_v1.0/css/sample.css" />
        <link rel="stylesheet" href="/etp_style_v1.0/css/member.css" />
        <style type="text/css">
            .m_colContainer .col-l { width: 240px; }
        </style>
    </head>
    <body>
        <div class="m_topContainer">
            <?php echo $this->layout()->top;?>
        </div>
        <div class="m_headerContainer">
            <?php echo $this->layout()->innerHeader;?>
        </div>
        <div class="container-fluid">
            <div class="m_colContainer">
                <div class="min_width clearfix">
                    <div class="m_colWrap clearfix">
                        <div class="col-l f14">
                            <?php echo $this->layout()->left;?>
                        </div>
                        <div class="col-r">
                            <div class="top clearfix"></div>
                            <?php echo $this->layout()->content;?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="m_footerContainer">
            <?php echo $this->layout()->footer;?>
        </div>
    </body>
    <script type="text/javascript">
        $(function() {
            <?php 
                if ( isset( $this->layout()->activeMenu ) ) {
                    echo '$(".'. $this->layout()->activeMenu .'").addClass("active");';
                }
            ?>  
        });
    </script>
</html>